INSERT INTO Specialty (name) VALUES ('Cardiology');
INSERT INTO Specialty (name) VALUES ('Dermatology');
INSERT INTO Specialty (name) VALUES ('Neurology');
INSERT INTO Specialty (name) VALUES ('Pediatrics');
INSERT INTO Specialty (name) VALUES ('Ophthalmology');
INSERT INTO Specialty (name) VALUES ('Gastroenterology');
INSERT INTO Specialty (name) VALUES ('Psychiatry');
INSERT INTO Specialty (name) VALUES ('Oncology');
INSERT INTO Specialty (name) VALUES ('Endocrinology');
INSERT INTO Specialty (name) VALUES ('Rheumatology');
INSERT INTO Specialty (name) VALUES ('Pulmonology');
INSERT INTO Specialty (name) VALUES ('Nephrology');

INSERT INTO Clinic (name, address, phone_number) VALUES ('Green Clinic', '123 Green St', '555-1234');
INSERT INTO Clinic (name, address, phone_number) VALUES ('Blue Clinic', '456 Blue Ave', '555-5678');
INSERT INTO Clinic (name, address, phone_number) VALUES ('Red Clinic', '789 Red Blvd', '555-9101');
INSERT INTO Clinic (name, address, phone_number) VALUES ('Yellow Clinic', '321 Yellow Ln', '555-1213');
INSERT INTO Clinic (name, address, phone_number) VALUES ('Orange Clinic', '654 Orange St', '555-1415');
INSERT INTO Clinic (name, address, phone_number) VALUES ('Purple Clinic', '987 Purple Ave', '555-1617');
INSERT INTO Clinic (name, address, phone_number) VALUES ('Magenta Clinic', '246 Magenta Blvd', '555-1819');
INSERT INTO Clinic (name, address, phone_number) VALUES ('Cyan Clinic', '369 Cyan Ln', '555-2021');

INSERT INTO Doctor (name, specialty_id, clinic_id) VALUES ('Dr. Smith', 1, 1);
INSERT INTO Doctor (name, specialty_id, clinic_id) VALUES ('Dr. Jones', 2, 1);
INSERT INTO Doctor (name, specialty_id, clinic_id) VALUES ('Dr. Brown', 3, 2);
INSERT INTO Doctor (name, specialty_id, clinic_id) VALUES ('Dr. Green', 4, 3);
INSERT INTO Doctor (name, specialty_id, clinic_id) VALUES ('Dr. Black', 5, 3);
INSERT INTO Doctor (name, specialty_id, clinic_id) VALUES ('Dr. White', 6, 4);
INSERT INTO Doctor (name, specialty_id, clinic_id) VALUES ('Dr. Gray', 7, 5);
INSERT INTO Doctor (name, specialty_id, clinic_id) VALUES ('Dr. Pink', 8, 5);
INSERT INTO Doctor (name, specialty_id, clinic_id) VALUES ('Dr. Gold', 9, 6);
INSERT INTO Doctor (name, specialty_id, clinic_id) VALUES ('Dr. Silver', 10, 7);
INSERT INTO Doctor (name, specialty_id, clinic_id) VALUES ('Dr. Bronze', 11, 7);
INSERT INTO Doctor (name, specialty_id, clinic_id) VALUES ('Dr. Copper', 12, 8);